zmq:
    # Receive temperatures port
    port_temp: 5588
    # Receive signal port
    port_sig: 5589
    # Send gr settings port
    port_send: 5555

    
bokeh:
    Periodogram:
        per_window: "boxcar"
        fA: 1e6/100
    sensor_count: 3
    p_update: 60
    title_font_size: "25px"
    label_font_size: "20px"
    legend_font_size: "15px"

    Temperature_Plot:
        sensor_name_list: (5,10,14)
        x_range_interval: 500
        x_range_padding: 0
        title: "Sensor Temperature"
        ylabel: "Temperature [°C]"
        xlabel: "Time"
        y_range: (0,40)
        plot_height: 950
        plot_width: 1180#930
        tools: "xpan,box_zoom,save,reset"
        y_axis_location: "left"
        sensor_names: "['5', '10', '14']"
        
    Spectrum_Plot:
        y_range: (10**-13, 1)
        x_range: (-2500, 2500)
        x_bounds: (-4000,4000)
        plot_height: 950#800
        plot_width: 1180#930
        xlabel: "Frequency [Hz]"
        ylabel: "Spectrum"
        title: "Periodogram of baseband signal"
        tools: "xpan,xbox_zoom,save,reset"

    Input_Controls:
        Title:
            sensor_count_input: "Sensor Count"
            polycoeff_input: "Polynomial Coefficients (of 5th harmonic)"
            offset_input: "Offset"
            fshift_input: "Frequency Shift"
            fft_size_input: "FFT Size"
            samp_rate_input: "Sampling Rate"
            thres_input: "Peak Threshold"
            min_dist_input: "Min Peak Distance"
            harmonic_input: "Harmonic"
            apply_button: "Apply Settings"
            
        Value:
            sensor_count_input: "16"
            polycoeff_input:    "[[2.22769620e-02, -1.70367733e+00, -1.58914013e+01, 1.19999708e+08],
                                [3.75334018e-02, -2.24642587e+00, -3.69621493e+01, 1.20001284e+08],
                                [1.41016716e-02, -1.21260981e+00, -4.59088135e+01, 1.20001834e+08],
                                [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0],
                                [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0],
                                [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]"
            offset_input: "[[130.0, 200.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]"
            fshift_input: "(24e6 * 5) + 0.0"
            fft_size_input: "1024"
            samp_rate_input: "10000"
            thres_input: "0.03"
            min_dist_input: "1"
            harmonic_input: "['1', '2','3','4','5','6','7']"
            apply_button: "success"
            
    Lines:
        styles: "['solid','dashed','dotted','dotdash','dashdot']"
        colors: "black"
        line_width: 2
        
    Legend_Temp:
        location: "bottom_left"
        click_policy: "hide"
