INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SPECTRAL_ANALYSIS spectral_analysis)

FIND_PATH(
    SPECTRAL_ANALYSIS_INCLUDE_DIRS
    NAMES spectral_analysis/api.h
    HINTS $ENV{SPECTRAL_ANALYSIS_DIR}/include
        ${PC_SPECTRAL_ANALYSIS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SPECTRAL_ANALYSIS_LIBRARIES
    NAMES gnuradio-spectral_analysis
    HINTS $ENV{SPECTRAL_ANALYSIS_DIR}/lib
        ${PC_SPECTRAL_ANALYSIS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPECTRAL_ANALYSIS DEFAULT_MSG SPECTRAL_ANALYSIS_LIBRARIES SPECTRAL_ANALYSIS_INCLUDE_DIRS)
MARK_AS_ADVANCED(SPECTRAL_ANALYSIS_LIBRARIES SPECTRAL_ANALYSIS_INCLUDE_DIRS)

